import { existsSync, readFileSync, writeFileSync } from "fs";
import { execFileSync } from "child_process";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const css = readFileSync(join(__dirname, "themes/payview-saas.css"), "utf-8");
const generated = `// Auto-generated by build.mjs — do not edit manually
export const THEME_CSS = ${JSON.stringify(css)};\n`;

writeFileSync(join(__dirname, "theme-data.gen.ts"), generated);
console.log("[build] Generated theme-data.gen.ts");

const esbuildCandidates = [
  join(__dirname, "node_modules/.bin/esbuild"),
  join(__dirname, "../action-tracker/node_modules/.bin/esbuild")
];
const esbuild = esbuildCandidates.find((candidate) => existsSync(candidate));
if (!esbuild) {
  throw new Error("Cannot find esbuild. Run npm install in the plugin directory first.");
}

execFileSync(
  esbuild,
  ["main.ts", "--bundle", "--platform=browser", "--format=cjs", "--external:obsidian", "--outfile=main.js"],
  { cwd: __dirname, stdio: "inherit" }
);
